version: "3.7"
name: ch-test
volumes:
  minio_storage: null
services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data
    container_name: minio
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 1;
      /usr/bin/mc alias set myminio http://minio:9000 user password;
      /usr/bin/mc mb myminio/testbucket;
      /usr/bin/mc mb myminio/testbucket-log;
      exit 0;
      "
  clickhouse-writer:
    image: clickhouse/clickhouse-server:25.5
    depends_on:
      - minio
    container_name: ch-w
  clickhouse-reader:
    image: clickhouse/clickhouse-server:25.5
    depends_on:
      - minio
    container_name: ch-r
